apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/$ /ui permanent;
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingressHostName }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 8080
            path: /ui
            pathType: Prefix
          - backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  number: 8080
            path: /
            pathType: Prefix
