{
 "title": "Prediction Service",
 "description": "Energy Consumption forecasting (daily)",
 "time": { "from": "now-7d", "to": "now+1d" },
 "panels": [
  {
   "title": "Kepler (Energy Consumption)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"energy_consumption\")\r\n    |> range(start: -8d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"timeseries\" and\r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> map(fn: (r) =>  ({\r\n      r with _value: r._value / 3600000.0\r\n    }))"
    },
    {
     "query": "from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"forecasting\" and\r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> drop(columns:[\"input_size\", \"forecasting_time\"])\r\n    |> timeShift(duration: 1d, columns: [\"_time\"])\r\n    |> map(fn: (r) =>  ({\r\n      r with _value: r._value / 3600000.0\r\n    }))"
    }
   ]
  },
  {
   "title": "Absolute Percentage Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nforecast = from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"forecasting\" and\r\n        r._field == \"forecasting_value\" and \r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> drop(columns:[\"input_size\", \"forecasting_time\"])\r\n    |> timeShift(duration: 1d, columns: [\"_time\"])\r\n    |> map(fn: (r) =>  ({\r\n      r with _value: r._value / 3600000.0\r\n    }))\r\n    \r\noriginal = from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"timeseries\" and\r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> map(fn: (r) =>  ({\r\n      r with _value: r._value / 3600000.0\r\n    }))\r\n\r\n// Join\r\njoined = join(tables: {original: original, forecast: forecast}, on: [\"_time\"])\r\n\r\n// result\r\nresult = joined\r\n  |>map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: 100.0 * math.abs(x: r._value_original - r._value_forecast) / r._value_original\r\n  }))\r\n  \r\nresult"
    }
   ]
  },
  {
   "title": "Off confidence interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\n// Forecasting Upper\r\nforecasting_upper = from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"forecasting\" and\r\n        r._field == \"forecasting_upper\" and \r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> drop(columns: [\"input_size\", \"forecasting_time\"])\r\n    |> timeShift(duration: 1d, columns: [\"_time\"])\r\n    |> map(fn: (r) => ({\r\n      r with _value: r._value / 3600000.0\r\n    }))\r\n    |> rename(columns: {_value: \"forecasting_upper\"})\r\n\r\n// Forecasting Lower\r\nforecasting_lower = from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"forecasting\" and\r\n        r._field == \"forecasting_lower\" and \r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> drop(columns: [\"input_size\", \"forecasting_time\"])\r\n    |> timeShift(duration: 1d, columns: [\"_time\"])\r\n    |> map(fn: (r) => ({\r\n      r with _value: r._value / 3600000.0\r\n    }))\r\n    |> rename(columns: {_value: \"forecasting_lower\"})\r\n\r\n// Original Data\r\noriginal = from(bucket: \"energy_consumption\")\r\n    |> range(start: -7d)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"timeseries\" and\r\n        r.aggregation_interval == \"86400\" and \r\n        r.metricId == \"M04\" \r\n    )\r\n    |> map(fn: (r) => ({\r\n      r with _value: r._value / 3600000.0\r\n    }))\r\n    |> rename(columns: {_value: \"original\"})\r\n\r\n// Join original with forecasting_upper\r\nfirst_join = join(\r\n    tables: {original: original, forecast_upper: forecasting_upper},\r\n    on: [\"_time\"]\r\n)\r\n\r\n// Join the first result with forecasting_lower\r\nfinal_join = join(\r\n    tables: {first_join: first_join, forecast_lower: forecasting_lower},\r\n    on: [\"_time\"]\r\n)\r\n\r\n// Apply logic to compare and return 1 if conditions are met\r\nresult = final_join\r\n    |> map(fn: (r) => ({\r\n        r with \r\n        result: if r.original > r.forecasting_upper or r.original < r.forecasting_lower then 1 else 0\r\n    }))\r\n    |> keep(columns: [\"_time\", \"result\"])\r\n\r\nresult"
    }
   ]
  }
 ]
}