openapi: 3.1.0
info:
  title: Template web service
  description: This is a template of a web service
  contact:
    name: HIRO-MicroDataCenters
    email: all-hiro@hiro-microdatacenters.nl
  license:
    name: MIT
    url: https://github.com/HIRO-MicroDataCenters-BV/template-python/blob/main/LICENSE
  version: 0.1.0
servers:
- url: http://0.0.0.0:8080
paths:
  /prediction/{metricId}:
    get:
      description: Returns a time series metric
      operationId: get_metric_by_id
      parameters:
      - description: Id of the metric to return
        explode: false
        in: path
        name: metricId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            applicatin/json:
              schema:
                $ref: '#/components/schemas/Metric'
          description: successful operation
        "400":
          description: Invalid Id supplied
        "404":
          description: Metric not found
      summary: Retrieve historical and predicted time series by ID
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Metric:
      properties:
        metricId:
          title: metricId
          type: string
        timeseries:
          items:
            format: float
            type: number
          title: timeseries
          type: array
        forecasting_values:
          items:
            format: float
            type: number
          title: forecasting_values
          type: array
        forecasting_upper_bounds:
          items:
            format: float
            type: number
          title: forecasting_upper_bounds
          type: array
        forecasting_lower_bounds:
          items:
            format: float
            type: number
          title: forecasting_lower_bounds
          type: array
        forecasting_model:
          title: forecasting_model
          type: string
        forecasting_period:
          format: int32
          title: forecasting_period
          type: integer
        time:
          items:
            format: date
            type: string
          title: time
          type: array
        aggregation_interval:
          format: int64
          title: aggregation_interval
          type: integer
      title: Metric
